<a href="https://colab.research.google.com/github/FABYG6/DL_Redes_Neuronales_Basicas/blob/main/Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Taller: 1 Redes Neuronales Basicas
#Estudiante: Nidia garcia
#Objetivo: Comprender como funciona un perceptron.

In [ ]:
import numpy as np

print("NumPy esta listo")


NumPy esta listo


# Crear matriz de datos

In [ ]:
X = np.array([
    [0.80, 0.60, 0.70],
    [0.30, 0.40, 0.20],
    [0.90, 0.80, 0.90],
    [0.40, 0.30, 0.50]
])

print(X)
print("Forma de X:", X.shape)


[[0.8 0.6 0.7]
 [0.3 0.4 0.2]
 [0.9 0.8 0.9]
 [0.4 0.3 0.5]]
Forma de X: (4, 3)


#Definir Peso de la matriz

In [ ]:
W = np.array([0.5, 0.3, 0.2])
bias = -0.5

print("Pesos:", W)
print("Bias:", bias)


Pesos: [0.5 0.3 0.2]
Bias: -0.5


#Calculo de la Matriz

In [ ]:
Z = X @ W + bias

print("Resultado antes de decidir:")
print(Z)


Resultado antes de decidir:
[ 0.22 -0.19  0.37 -0.11]


#Activación


In [ ]:
def funcion_escalon(z):
    return np.where(z >= 0, 1, 0)

prediccion = funcion_escalon(Z)

print("Predicciones:")
print(prediccion)


Predicciones:
[1 0 1 0]


#vectorización

In [ ]:
Z = X @ W + bias

#peso para tres neuronas

In [ ]:
W1 = np.array([
    [0.5, 0.2, 0.4],
    [0.3, 0.6, 0.1],
    [0.2, 0.4, 0.7]
])

b1 = np.array([0.1, 0.1, 0.1])

Z1 = X @ W1 + b1
print(Z1)
print("Forma:", Z1.shape)


[[0.82 0.9  0.97]
 [0.41 0.48 0.4 ]
 [0.97 1.12 1.17]
 [0.49 0.56 0.64]]
Forma: (4, 3)


In [ ]:
def relu(z):
    return np.maximum(0, z)

A1 = relu(Z1)
print(A1)


[[0.82 0.9  0.97]
 [0.41 0.48 0.4 ]
 [0.97 1.12 1.17]
 [0.49 0.56 0.64]]


In [ ]:
W2 = np.array([
    [0.4],
    [0.6],
    [0.5]
])

b2 = np.array([0.1])

Z2 = A1 @ W2 + b2
print(Z2)


[[1.453]
 [0.752]
 [1.745]
 [0.952]]


In [ ]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

A2 = sigmoid(Z2)
print("Valores entre 0 y 1:")
print(A2)

prediccion_final = np.where(A2 >= 0.5, 1, 0)
print("Prediccion final:")
print(prediccion_final)


Valores entre 0 y 1:
[[0.81045971]
 [0.67961433]
 [0.85132105]
 [0.72151722]]
Prediccion final:
[[1]
 [1]
 [1]
 [1]]
